# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi-2.json:
  spec:
    # ignore parameters.items.description & parameters.items.deprecated
    - >-
      #/paths/~1Destiny2~1{membershipType}~1Profile~1{destinyMembershipId}~1/get/parameters/0/items/description
    - >-
      #/paths/~1Destiny2~1{membershipType}~1Profile~1{destinyMembershipId}~1Character~1{characterId}~1/get/parameters/1/items/description
    - >-
      #/paths/~1Destiny2~1{membershipType}~1Profile~1{destinyMembershipId}~1Item~1{itemInstanceId}~1/get/parameters/0/items/description
    - >-
      #/paths/~1Destiny2~1{membershipType}~1Profile~1{destinyMembershipId}~1Character~1{characterId}~1Vendors~1/get/parameters/1/items/description
    - >-
      #/paths/~1Destiny2~1{membershipType}~1Profile~1{destinyMembershipId}~1Character~1{characterId}~1Vendors~1{vendorHash}~1/get/parameters/1/items/description
    - "#/paths/~1Destiny2~1Vendors~1/get/parameters/0/items/description"
    - >-
      #/paths/~1Destiny2~1{membershipType}~1Profile~1{destinyMembershipId}~1Character~1{characterId}~1Collectibles~1{collectiblePresentationNodeHash}~1/get/parameters/2/items/description
    - >-
      #/paths/~1Destiny2~1{membershipType}~1Account~1{destinyMembershipId}~1Character~1{characterId}~1Stats~1/get/parameters/4/items/description
    - >-
      #/paths/~1Destiny2~1{membershipType}~1Account~1{destinyMembershipId}~1Character~1{characterId}~1Stats~1/get/parameters/6/items/description
    - >-
      #/paths/~1Destiny2~1{membershipType}~1Account~1{destinyMembershipId}~1Stats~1/get/parameters/1/items/description
    - >-
      #/paths/~1Fireteam~1Clan~1{groupId}~1My~1{platform}~1{includeClosed}~1{page}~1/get/parameters/4/deprecated
