components:
  schemas:
    ApplicationScopes:
      type: integer
      format: int64
      enum:
        - 1
        - 2
        - 4
        - 8
        - 16
        - 32
        - 64
        - 128
        - 256
        - 512
        - 1024
        - 2048
        - 4096
      x-enum-values:
        - numericValue: "1"
          identifier: ReadBasicUserProfile
          description: Read basic user profile information such as the user's handle, avatar icon, etc.
        - numericValue: "2"
          identifier: ReadGroups
          description: Read Group/Clan Forums, Wall, and Members for groups and clans that the user has joined.
        - numericValue: "4"
          identifier: WriteGroups
          description: Write Group/Clan Forums, Wall, and Members for groups and clans that the user has joined.
        - numericValue: "8"
          identifier: AdminGroups
          description: Administer Group/Clan Forums, Wall, and Members for groups and clans that the user is a founder or an administrator.
        - numericValue: "16"
          identifier: BnetWrite
          description: 'Create new groups, clans, and forum posts, along with other actions that are reserved for Bungie.net elevated scope: not meant to be used by third party applications.'
        - numericValue: "32"
          identifier: MoveEquipDestinyItems
          description: Move or equip Destiny items
        - numericValue: "64"
          identifier: ReadDestinyInventoryAndVault
          description: Read Destiny 1 Inventory and Vault contents. For Destiny 2, this scope is needed to read anything regarded as private. This is the only scope a Destiny 2 app needs for read operations against Destiny 2 data such as inventory, vault, currency, vendors, milestones, progression, etc.
        - numericValue: "128"
          identifier: ReadUserData
          description: Read user data such as who they are web notifications, clan/group memberships, recent activity, muted users.
        - numericValue: "256"
          identifier: EditUserData
          description: Edit user data such as preferred language, status, motto, avatar selection and theme.
        - numericValue: "512"
          identifier: ReadDestinyVendorsAndAdvisors
          description: Access vendor and advisor data specific to a user. OBSOLETE. This scope is only used on the Destiny 1 API.
        - numericValue: "1024"
          identifier: ReadAndApplyTokens
          description: Read offer history and claim and apply tokens for the user.
        - numericValue: "2048"
          identifier: AdvancedWriteActions
          description: Can perform actions that will result in a prompt to the user via the Destiny app.
        - numericValue: "4096"
          identifier: PartnerOfferGrant
          description: Can user the partner offer api to claim rewards defined for a partner

    ApiUsage:
      type: object
      properties:
        apiCalls:
          type: array
          description: Counts for on API calls made for the time range.
          items:
            $ref: '#/components/schemas/Series'
        throttledRequests:
          type: array
          description: Instances of blocked requests or requests that crossed the warn threshold during the time range.
          items:
            $ref: '#/components/schemas/Series'

    Series:
      type: object
      properties:
        datapoints:
          type: array
          description: Collection of samples with time and value.
          items:
            $ref: '#/components/schemas/Datapoint'
        target:
          type: string
          description: Target to which to datapoints apply.

    Datapoint:
      type: object
      properties:
        time:
          type: string
          description: Timestamp for the related count.
          format: date-time
        count:
          type: number
          description: Count associated with timestamp
          format: double

    Application:
      type: object
      properties:
        applicationId:
          type: integer
          description: Unique ID assigned to the application
          format: int32
        name:
          type: string
          description: Name of the application
        redirectUrl:
          type: string
          description: URL used to pass the user's authorization code to the application
        link:
          type: string
          description: Link to website for the application where a user can learn more about the app.
        scope:
          type: integer
          description: Permissions the application needs to work
          format: int64
        origin:
          type: string
          description: Value of the Origin header sent in requests generated by this application.
        status:
          type: integer
          description: Current status of the application.
          format: int32
          x-enum-reference:
            $ref: '#/components/schemas/ApplicationStatus'
        creationDate:
          type: string
          description: Date the application was first added to our database.
          format: date-time
        statusChanged:
          type: string
          description: Date the application status last changed.
          format: date-time
        firstPublished:
          type: string
          description: Date the first time the application status entered the 'Public' status.
          format: date-time
        team:
          type: array
          description: List of team members who manage this application on Bungie.net. Will always consist of at least the application owner.
          items:
            $ref: '#/components/schemas/ApplicationDeveloper'

    ApplicationStatus:
      type: integer
      format: int32
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
      x-enum-values:
        - numericValue: "0"
          identifier: None
          description: No value assigned
        - numericValue: "1"
          identifier: Private
          description: Application exists and works but will not appear in any public catalog. New applications start in this state, test applications will remain in this state.
        - numericValue: "2"
          identifier: Public
          description: Active applications that can appear in an catalog.
        - numericValue: "3"
          identifier: Disabled
          description: Application disabled by the owner. All authorizations will be treated as terminated while in this state. Owner can move back to private or public state.
        - numericValue: "4"
          identifier: Blocked
          description: Application has been blocked by Bungie. It cannot be transitioned out of this state by the owner. Authorizations are terminated when an application is in this state.

    ApplicationDeveloper:
      type: object
      properties:
        role:
          type: integer
          format: int32
          x-enum-reference:
            $ref: '#/components/schemas/DeveloperRole'
        apiEulaVersion:
          type: integer
          format: int32
        user:
          $ref: 'user.yml#/components/schemas/UserInfoCard'

    DeveloperRole:
      type: integer
      format: int32
      enum:
        - 0
        - 1
        - 2
      x-enum-values:
        - numericValue: "0"
          identifier: None
        - numericValue: "1"
          identifier: Owner
        - numericValue: "2"
          identifier: TeamMember

