openapi: 3.0.1
info:
  title: Bungie.Net API
  description:
    These endpoints constitute the functionality exposed by Bungie.net,
    both for more traditional website functionality and for connectivity to Bungie
    video games and their related functionality.
  termsOfService: https://www.bungie.net/en/View/Bungie/terms
  contact:
    name: Bungie.net API Support
    url: https://github.com/Bungie-net/api
    email: support@bungie.com
  license:
    name: BSD License 2.0
    url: https://github.com/Bungie-net/api/blob/master/LICENSE
  version: 2.10.0
servers:
  - url: https://bungie.com/Platform

components:
  securitySchemes:
    apiKey:
      type: apiKey
      description:
        Every request requires an API key.  To get an API key, register
        a new application at https://www.bungie.net/en/Application.
      name: X-API-Key
      in: header
    oauth2:
      type: oauth2
      description:
        For requests that require Authentication, you will need to have
        your users authenticate via our OAuth mechanisms.  See https://github.com/Bungie-net/api/wiki/OAuth-Documentation
        for more details.
      flows:
        authorizationCode:
          authorizationUrl: https://www.bungie.net/en/OAuth/Authorize
          tokenUrl: https://www.bungie.net/Platform/App/OAuth/token/
          scopes:
            ReadBasicUserProfile:
              Read basic user profile information such as the
              user's handle, avatar icon, etc.
            ReadGroups:
              "Read Group/Clan Forums, Wall, and Members for groups and
              clans that the user has joined."
            WriteGroups:
              "Write Group/Clan Forums, Wall, and Members for groups and
              clans that the user has joined."
            AdminGroups:
              "Administer Group/Clan Forums, Wall, and Members for groups
              and clans that the user is a founder or an administrator."
            BnetWrite:
              "Create new groups, clans, and forum posts, along with other
              actions that are reserved for Bungie.netelevated scope: not meant
              to be used by third party applications."
            MoveEquipDestinyItems: Move or equip Destiny items
            ReadDestinyInventoryAndVault:
              "Read Destiny 1 Inventory and Vault contents.
              For Destiny 2, this scope is needed to read anything regarded as private.
              This is the only scope aDestiny 2 app needs for read operations
              against Destiny 2 data such as inventory, vault, currency,vendors,
              milestones, progression, etc."
            ReadUserData:
              "Read user data such as who they are web notifications,
              clan/group memberships, recent activity, muted users."
            EditUserData:
              Edit user data such as preferred language, status, motto,
              avatar selection and theme.
            ReadDestinyVendorsAndAdvisors:
              Access vendor and advisor data specific
              to a user. OBSOLETE. This scope is only used on the Destiny 1 API.
            ReadAndApplyTokens:
              Read offer history and claim and apply tokens for
              the user.
            AdvancedWriteActions:
              Can perform actions that will result in a prompt
              to the user via the Destiny app.
            PartnerOfferGrant:
              Can user the partner offer api to claim rewards defined
              for a partner

paths:
  /App/ApiUsage/{applicationId}/:
    get:
      tags:
        - App
      description:
        Get API usage by application for time frame specified. You can
        go as far back as 30 days ago, and can ask for up to a 48 hour window of time
        in a single request. You must be authenticated with at least the ReadUserData
        permission to access this endpoint.
      operationId: App.GetApplicationApiUsage
      deprecated: false
      security:
        - oauth2:
            - ReadUserData
  /App/FirstParty/:
    get:
      tags:
        - App
      description: Get list of applications created by Bungie.
      operationId: App.GetBungieApplications
      deprecated: false
  /User/GetBungieNetUserById/{id}/:
    get:
      tags:
        - User
      description: Loads a bungienet user by membership id.
      operationId: User.GetBungieNetUserById
      deprecated: false
  /User/SearchUsers/:
    get:
      tags:
        - User
      description: Returns a list of possible users based on the search string
      operationId: User.SearchUsers
      deprecated: false
  /User/GetCredentialTypesForTargetAccount/{membershipId}/:
    get:
      tags:
        - User
      description: Returns a list of credential types attached to the requested account
      operationId: User.GetCredentialTypesForTargetAccount
      deprecated: false
  /User/GetAvailableThemes/:
    get:
      tags:
        - User
      description: Returns a list of all available user themes.
      operationId: User.GetAvailableThemes
      deprecated: false
  /User/GetMembershipsById/{membershipId}/{membershipType}/:
    get:
      tags:
        - User
      description:
        Returns a list of accounts associated with the supplied membership
        ID and membership type. This will include all linked accounts (even when hidden)
        if supplied credentials permit it.
      operationId: User.GetMembershipDataById
      deprecated: false
  /User/GetMembershipsForCurrentUser/:
    get:
      tags:
        - User
      description:
        Returns a list of accounts associated with signed in user. This
        is useful for OAuth implementations that do not give you access to the token
        response.
      operationId: User.GetMembershipDataForCurrentUser
      deprecated: false
      security:
        - oauth2:
            - ReadBasicUserProfile
  /User/GetMembershipFromHardLinkedCredential/{crType}/{credential}/:
    get:
      tags:
        - User
      description:
        Gets any hard linked membership given a credential. Only works
        for credentials that are public (just SteamID64 right now). Cross Save aware.
      operationId: User.GetMembershipFromHardLinkedCredential
      deprecated: false
  /Content/GetContentType/{type}/:
    get:
      tags:
        - Content
      description: Gets an object describing a particular variant of content.
      operationId: Content.GetContentType
      deprecated: false
  /Content/GetContentById/{id}/{locale}/:
    get:
      tags:
        - Content
      description: Returns a content item referenced by id
      operationId: Content.GetContentById
      deprecated: false
  /Content/GetContentByTagAndType/{tag}/{type}/{locale}/:
    get:
      tags:
        - Content
      description: Returns the newest item that matches a given tag and Content Type.
      operationId: Content.GetContentByTagAndType
      deprecated: false
  /Content/Search/{locale}/:
    get:
      tags:
        - Content
      description:
        Gets content based on querystring information passed in. Provides
        basic search and text search capabilities.
      operationId: Content.SearchContentWithText
      deprecated: false
  /Content/SearchContentByTagAndType/{tag}/{type}/{locale}/:
    get:
      tags:
        - Content
      description:
        Searches for Content Items that match the given Tag and Content
        Type.
      operationId: Content.SearchContentByTagAndType
      deprecated: false
  /Content/SearchHelpArticles/{searchtext}/{size}/:
    get:
      tags:
        - Content
      description: Search for Help Articles.
      operationId: Content.SearchHelpArticles
      deprecated: false

  /Forum/GetTopicsPaged/{page}/{pageSize}/{group}/{sort}/{quickDate}/{categoryFilter}/:
    get:
      tags:
        - Forum
      description: Get topics from any forum.
      operationId: Forum.GetTopicsPaged
      deprecated: false
  /Forum/GetCoreTopicsPaged/{page}/{sort}/{quickDate}/{categoryFilter}/:
    get:
      tags:
        - Forum
      description: Gets a listing of all topics marked as part of the core group.
      operationId: Forum.GetCoreTopicsPaged
      deprecated: false
  /Forum/GetPostsThreadedPaged/{parentPostId}/{page}/{pageSize}/{replySize}/{getParentPost}/{rootThreadMode}/{sortMode}/:
    get:
      tags:
        - Forum
      description:
        Returns a thread of posts at the given parent, optionally returning
        replies to those posts as well as the original parent.
      operationId: Forum.GetPostsThreadedPaged
      deprecated: false
  /Forum/GetPostsThreadedPagedFromChild/{childPostId}/{page}/{pageSize}/{replySize}/{rootThreadMode}/{sortMode}/: 
    get:
      tags:
        - Forum
      description:
        Returns a thread of posts starting at the topicId of the input
        childPostId, optionally returning replies to those posts as well as the original
        parent.
      operationId: Forum.GetPostsThreadedPagedFromChild
      deprecated: false
  /Forum/GetPostAndParent/{childPostId}/:
    get:
      tags:
        - Forum
      description: Returns the post specified and its immediate parent.
      operationId: Forum.GetPostAndParent
      deprecated: false
  /Forum/GetPostAndParentAwaitingApproval/{childPostId}/:
    get:
      tags:
        - Forum
      description:
        Returns the post specified and its immediate parent of posts that
        are awaiting approval.
      operationId: Forum.GetPostAndParentAwaitingApproval
      deprecated: false
  /Forum/GetTopicForContent/{contentId}/:
    get:
      tags:
        - Forum
      description: Gets the post Id for the given content item's comments, if it exists.
      operationId: Forum.GetTopicForContent
      deprecated: false
  /Forum/GetForumTagSuggestions/:
    get:
      tags:
        - Forum
      description:
        Gets tag suggestions based on partial text entry, matching them
        with other tags previously used in the forums.
      operationId: Forum.GetForumTagSuggestions
      deprecated: false
  /Forum/Poll/{topicId}/:
    get:
      tags:
        - Forum
      description: Gets the specified forum poll.
      operationId: Forum.GetPoll
      deprecated: false
  /Forum/Recruit/Summaries/:
    post:
      tags:
        - Forum
      description:
        Allows the caller to get a list of to 25 recruitment thread summary
        information objects.
      operationId: Forum.GetRecruitmentThreadSummaries
      deprecated: false
  /GroupV2/GetAvailableAvatars/:
    get:
      tags:
        - GroupV2
      description:
        Returns a list of all available group avatars for the signed-in
        user.
      operationId: GroupV2.GetAvailableAvatars
      deprecated: false
  /GroupV2/GetAvailableThemes/:
    get:
      tags:
        - GroupV2
      description: Returns a list of all available group themes.
      operationId: GroupV2.GetAvailableThemes
      deprecated: false
  /GroupV2/GetUserClanInviteSetting/{mType}/:
    get:
      tags:
        - GroupV2
      description:
        Gets the state of the user's clan invite preferences for a particular
        membership type - true if they wish to be invited to clans, false otherwise.
      operationId: GroupV2.GetUserClanInviteSetting
      deprecated: false
      security:
        - oauth2:
            - ReadUserData
  /GroupV2/Recommended/{groupType}/{createDateRange}/:
    post:
      tags:
        - GroupV2
      description:
        Gets groups recommended for you based on the groups to whom those
        you follow belong.
      operationId: GroupV2.GetRecommendedGroups
      deprecated: false
      security:
        - oauth2:
            - ReadGroups
  /GroupV2/Search/:
    post:
      tags:
        - GroupV2
      description: Search for Groups.
      operationId: GroupV2.GroupSearch
      deprecated: false
  /GroupV2/{groupId}/:
    get:
      tags:
        - GroupV2
      description: Get information about a specific group of the given ID.
      operationId: GroupV2.GetGroup
      deprecated: false
  /GroupV2/Name/{groupName}/{groupType}/:
    get:
      tags:
        - GroupV2
      description:
        Get information about a specific group with the given name and
        type.
      operationId: GroupV2.GetGroupByName
      deprecated: false
  /GroupV2/NameV2/:
    post:
      tags:
        - GroupV2
      description:
        Get information about a specific group with the given name and
        type. The POST version.
      operationId: GroupV2.GetGroupByNameV2
      deprecated: false
  /GroupV2/{groupId}/OptionalConversations/:
    get:
      tags:
        - GroupV2
      description:
        Gets a list of available optional conversation channels and their
        settings.
      operationId: GroupV2.GetGroupOptionalConversations
      deprecated: false
  /GroupV2/{groupId}/Edit/:
    post:
      tags:
        - GroupV2
      description:
        Edit an existing group. You must have suitable permissions in the
        group to perform this operation. This latest revision will only edit the fields
        you pass in - pass null for properties you want to leave unaltered.
      operationId: GroupV2.EditGroup
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/EditClanBanner/:
    post:
      tags:
        - GroupV2
      description:
        Edit an existing group's clan banner. You must have suitable permissions
        in the group to perform this operation. All fields are required.
      operationId: GroupV2.EditClanBanner
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/EditFounderOptions/:
    post:
      tags:
        - GroupV2
      description:
        Edit group options only available to a founder. You must have suitable
        permissions in the group to perform this operation.
      operationId: GroupV2.EditFounderOptions
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/OptionalConversations/Add/:
    post:
      tags:
        - GroupV2
      description:
        Add a new optional conversation/chat channel. Requires admin permissions
        to the group.
      operationId: GroupV2.AddOptionalConversation
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/OptionalConversations/Edit/{conversationId}/:
    post:
      tags:
        - GroupV2
      description:
        Edit the settings of an optional conversation/chat channel. Requires
        admin permissions to the group.
      operationId: GroupV2.EditOptionalConversation
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/Members/:
    get:
      tags:
        - GroupV2
      description: Get the list of members in a given group.
      operationId: GroupV2.GetMembersOfGroup
      deprecated: false
  /GroupV2/{groupId}/AdminsAndFounder/:
    get:
      tags:
        - GroupV2
      description:
        Get the list of members in a given group who are of admin level
        or higher.
      operationId: GroupV2.GetAdminsAndFounderOfGroup
      deprecated: false
  /GroupV2/{groupId}/Members/{membershipType}/{membershipId}/SetMembershipType/{memberType}/:
     post:
      tags:
        - GroupV2
      description:
        Edit the membership type of a given member. You must have suitable
        permissions in the group to perform this operation.
      operationId: GroupV2.EditGroupMembership
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/Members/{membershipType}/{membershipId}/Kick/:
    post:
      tags:
        - GroupV2
      description:
        Kick a member from the given group, forcing them to reapply if
        they wish to re-join the group. You must have suitable permissions in the
        group to perform this operation.
      operationId: GroupV2.KickMember
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/Members/{membershipType}/{membershipId}/Ban/:
    post:
      tags:
        - GroupV2
      description:
        Bans the requested member from the requested group for the specified
        period of time.
      operationId: GroupV2.BanMember
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/Members/{membershipType}/{membershipId}/Unban/:
    post:
      tags:
        - GroupV2
      description: Unbans the requested member, allowing them to re-apply for membership.
      operationId: GroupV2.UnbanMember
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/Banned/:
    get:
      tags:
        - GroupV2
      description:
        Get the list of banned members in a given group. Only accessible
        to group Admins and above. Not applicable to all groups. Check group features.
      operationId: GroupV2.GetBannedMembersOfGroup
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/Admin/AbdicateFoundership/{membershipType}/{founderIdNew}/:
    post:
      tags:
        - GroupV2
      description:
        An administrative method to allow the founder of a group or clan
        to give up their position to another admin permanently.
      operationId: GroupV2.AbdicateFoundership
      deprecated: false
  /GroupV2/{groupId}/Members/Pending/:
    get:
      tags:
        - GroupV2
      description:
        Get the list of users who are awaiting a decision on their application
        to join a given group. Modified to include application info.
      operationId: GroupV2.GetPendingMemberships
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/Members/InvitedIndividuals/:
    get:
      tags:
        - GroupV2
      description: Get the list of users who have been invited into the group.
      operationId: GroupV2.GetInvitedIndividuals
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/Members/ApproveAll/:
    post:
      tags:
        - GroupV2
      description: Approve all of the pending users for the given group.
      operationId: GroupV2.ApproveAllPending
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/Members/DenyAll/:
    post:
      tags:
        - GroupV2
      description: Deny all of the pending users for the given group.
      operationId: GroupV2.DenyAllPending
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/Members/ApproveList/:
    post:
      tags:
        - GroupV2
      description: Approve all of the pending users for the given group.
      operationId: GroupV2.ApprovePendingForList
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/Members/Approve/{membershipType}/{membershipId}/:
    post:
      tags:
        - GroupV2
      description:
        Approve the given membershipId to join the group/clan as long as
        they have applied.
      operationId: GroupV2.ApprovePending
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/Members/DenyList/:
    post:
      tags:
        - GroupV2
      description:
        Deny all of the pending users for the given group that match the
        passed-in .
      operationId: GroupV2.DenyPendingForList
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/User/{membershipType}/{membershipId}/{filter}/{groupType}/:
    get:
      tags:
        - GroupV2
      description: Get information about the groups that a given member has joined.
      operationId: GroupV2.GetGroupsForMember
      deprecated: false
  /GroupV2/Recover/{membershipType}/{membershipId}/{groupType}/:
    get:
      tags:
        - GroupV2
      description:
        Allows a founder to manually recover a group they can see in game
        but not on bungie.net
      operationId: GroupV2.RecoverGroupForFounder
      deprecated: false
  /GroupV2/User/Potential/{membershipType}/{membershipId}/{filter}/{groupType}/:
    get:
      tags:
        - GroupV2
      description:
        Get information about the groups that a given member has applied
        to or been invited to.
      operationId: GroupV2.GetPotentialGroupsForMember
      deprecated: false
  /GroupV2/{groupId}/Members/IndividualInvite/{membershipType}/{membershipId}/:
    post:
      tags:
        - GroupV2
      description: Invite a user to join this group.
      operationId: GroupV2.IndividualGroupInvite
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /GroupV2/{groupId}/Members/IndividualInviteCancel/{membershipType}/{membershipId}/:
    post:
      tags:
        - GroupV2
      description: Cancels a pending invitation to join a group.
      operationId: GroupV2.IndividualGroupInviteCancel
      deprecated: false
      security:
        - oauth2:
            - AdminGroups
  /Tokens/Partner/ClaimOffer/:
    post:
      tags:
        - Tokens
      description: Claim a partner offer as the authenticated user.
      operationId: Tokens.ClaimPartnerOffer
      deprecated: false
      security:
        - oauth2:
            - PartnerOfferGrant
  /Tokens/Partner/ApplyMissingOffers/{partnerApplicationId}/{targetBnetMembershipId}/:
    post:
      tags:
        - Tokens
      description:
        Apply a partner offer to the targeted user. This endpoint does
        not claim a new offer, but any already claimed offers will be applied to the
        game if not already.
      operationId: Tokens.ApplyMissingPartnerOffersWithoutClaim
      deprecated: false
      security:
        - oauth2:
            - PartnerOfferGrant
  /Tokens/Partner/History/{partnerApplicationId}/{targetBnetMembershipId}/:
    get:
      tags:
        - Tokens
      description:
        Returns the partner sku and offer history of the targeted user.
        Elevated permissions are required to see users that are not yourself.
      operationId: Tokens.GetPartnerOfferSkuHistory
      deprecated: false
      security:
        - oauth2:
            - PartnerOfferGrant
  /Destiny2/Manifest/:
    get:
      tags:
        - Destiny2
      description: Returns the current version of the manifest as a json object.
      operationId: Destiny2.GetDestinyManifest
      deprecated: false
  /Destiny2/Manifest/{entityType}/{hashIdentifier}/:
    get:
      tags:
        - Destiny2
      description:
        Returns the static definition of an entity of the given Type and
        hash identifier. Examine the API Documentation for the Type Names of entities
        that have their own components/schemas. Note that the return type will always
        *inherit from* DestinyDefinition, but the specific type returned will be the
        requested entity type if it can be found. Please don't use this as a chatty
        alternative to the Manifest database if you require large sets of data, but
        for simple and one-off accesses this should be handy.
      operationId: Destiny2.GetDestinyEntityDefinition
      deprecated: false
  /Destiny2/SearchDestinyPlayer/{membershipType}/{displayName}/:
    get:
      tags:
        - Destiny2
      description:
        Returns a list of Destiny memberships given a full Gamertag or
        PSN ID. Unless you pass returnOriginalProfile=true, this will return membership
        information for the users' Primary Cross Save Profile if they are engaged
        in cross save rather than any original Destiny profile that is now being overridden.
      operationId: Destiny2.SearchDestinyPlayer
      deprecated: false
  /Destiny2/{membershipType}/Profile/{membershipId}/LinkedProfiles/:
    get:
      tags:
        - Destiny2
      description:
        Returns a summary information about all profiles linked to the
        requesting membership type/membership ID that have valid Destiny information.
        The passed-in Membership Type/Membership ID may be a Bungie.Net membership
        or a Destiny membership. It only returns the minimal amount of data to begin
        making more substantive requests, but will hopefully serve as a useful alternative
        to UserServices for people who just care about Destiny data. Note that it
        will only return linked accounts whose linkages you are allowed to view.
      operationId: Destiny2.GetLinkedProfiles
      deprecated: false
  /Destiny2/{membershipType}/Profile/{destinyMembershipId}/:
    get:
      tags:
        - Destiny2
      description: Returns Destiny Profile information for the supplied membership.
      operationId: Destiny2.GetProfile
      deprecated: false
  /Destiny2/{membershipType}/Profile/{destinyMembershipId}/Character/{characterId}/:
    get:
      tags:
        - Destiny2
      description: Returns character information for the supplied character.
      operationId: Destiny2.GetCharacter
      deprecated: false
  /Destiny2/Clan/{groupId}/WeeklyRewardState/:
    get:
      tags:
        - Destiny2
      description:
        Returns information on the weekly clan rewards and if the clan
        has earned them or not. Note that this will always report rewards as not redeemed.
      operationId: Destiny2.GetClanWeeklyRewardState
      deprecated: false
  /Destiny2/{membershipType}/Profile/{destinyMembershipId}/Item/{itemInstanceId}/:
    get:
      tags:
        - Destiny2
      description:
        Retrieve the details of an instanced Destiny Item. An instanced
        Destiny item is one with an ItemInstanceId. Non-instanced items, such as materials,
        have no useful instance-specific details and thus are not queryable here.
      operationId: Destiny2.GetItem
      deprecated: false
  /Destiny2/{membershipType}/Profile/{destinyMembershipId}/Character/{characterId}/Vendors/:
    get:
      tags:
        - Destiny2
      description:
        Get currently available vendors from the list of vendors that can
        possibly have rotating inventory. Note that this does not include things like
        preview vendors and vendors-as-kiosks, neither of whom have rotating/dynamic
        inventories. Use their components/schemas as-is for those.
      operationId: Destiny2.GetVendors
      deprecated: false
  /Destiny2/{membershipType}/Profile/{destinyMembershipId}/Character/{characterId}/Vendors/{vendorHash}/:
    get:
      tags:
        - Destiny2
      description: Get the details of a specific Vendor.
      operationId: Destiny2.GetVendor
      deprecated: false
  /Destiny2/Vendors/:
    get:
      tags:
        - Destiny2
        - Preview
      description:
        "Get items available from vendors where the vendors have items
        for sale that are common for everyone. If any portion of the Vendor's available
        inventory is character or account specific, we will be unable to return their
        data from this endpoint due to the way that available inventory is computed.
        As I am often guilty of saying: 'It's a long story...'"
      operationId: Destiny2.GetPublicVendors
      deprecated: false
      x-preview: true
  /Destiny2/{membershipType}/Profile/{destinyMembershipId}/Character/{characterId}/Collectibles/{collectiblePresentationNodeHash}/:
    get:
      tags:
        - Destiny2
      description:
        Given a Presentation Node that has Collectibles as direct descendants,
        this will return item details about those descendants in the context of the
        requesting character.
      operationId: Destiny2.GetCollectibleNodeDetails
      deprecated: false
  /Destiny2/Actions/Items/TransferItem/:
    post:
      tags:
        - Destiny2
      description:
        Transfer an item to/from your vault. You must have a valid Destiny
        account. You must also pass BOTH a reference AND an instance ID if it's an
        instanced item. itshappening.gif
      operationId: Destiny2.TransferItem
      deprecated: false
      security:
        - oauth2:
            - MoveEquipDestinyItems
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "0.1"
  /Destiny2/Actions/Items/PullFromPostmaster/:
    post:
      tags:
        - Destiny2
      description:
        Extract an item from the Postmaster, with whatever implications
        that may entail. You must have a valid Destiny account. You must also pass
        BOTH a reference AND an instance ID if it's an instanced item.
      operationId: Destiny2.PullFromPostmaster
      deprecated: false
      security:
        - oauth2:
            - MoveEquipDestinyItems
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "0.1"
  /Destiny2/Actions/Items/EquipItem/:
    post:
      tags:
        - Destiny2
      description:
        Equip an item. You must have a valid Destiny Account, and either
        be in a social space, in orbit, or offline.
      operationId: Destiny2.EquipItem
      deprecated: false
      security:
        - oauth2:
            - MoveEquipDestinyItems
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "0.1"
  /Destiny2/Actions/Items/EquipItems/:
    post:
      tags:
        - Destiny2
      description:
        Equip a list of items by itemInstanceIds. You must have a valid
        Destiny Account, and either be in a social space, in orbit, or offline. Any
        items not found on your character will be ignored.
      operationId: Destiny2.EquipItems
      deprecated: false
      security:
        - oauth2:
            - MoveEquipDestinyItems
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "0.1"
  /Destiny2/Actions/Items/SetLockState/:
    post:
      tags:
        - Destiny2
      description:
        Set the Lock State for an instanced item. You must have a valid
        Destiny Account.
      operationId: Destiny2.SetItemLockState
      deprecated: false
      security:
        - oauth2:
            - MoveEquipDestinyItems
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "0.1"
  /Destiny2/Actions/Items/SetTrackedState/:
    post:
      tags:
        - Destiny2
      description:
        Set the Tracking State for an instanced item, if that item is a
        Quest or Bounty. You must have a valid Destiny Account. Yeah, it's an item.
      operationId: Destiny2.SetQuestTrackedState
      deprecated: false
      security:
        - oauth2:
            - MoveEquipDestinyItems
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "1"
  /Destiny2/Actions/Items/InsertSocketPlug/:
    post:
      tags:
        - Destiny2
        - Preview
      description:
        Insert a plug into a socketed item. I know how it sounds, but I
        assure you it's much more G-rated than you might be guessing. We haven't decided
        yet whether this will be able to insert plugs that have side effects, but
        if we do it will require special scope permission for an application attempting
        to do so. You must have a valid Destiny Account, and either be in a social
        space, in orbit, or offline. Request must include proof of permission for
        'InsertPlugs' from the account owner.
      operationId: Destiny2.InsertSocketPlug
      deprecated: false
      security:
        - oauth2:
            - AdvancedWriteActions
      x-preview: true
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "1"
  /Destiny2/Stats/PostGameCarnageReport/{activityId}/:
    get:
      tags:
        - Destiny2
      description: Gets the available post game carnage report for the activity ID.
      operationId: Destiny2.GetPostGameCarnageReport
      deprecated: false
  /Destiny2/Stats/PostGameCarnageReport/{activityId}/Report/:
    post:
      tags:
        - Destiny2
      description:
        Report a player that you met in an activity that was engaging in
        ToS-violating activities. Both you and the offending player must have played
        in the activityId passed in. Please use this judiciously and only when you
        have strong suspicions of violation, pretty please.
      operationId: Destiny2.ReportOffensivePostGameCarnageReportPlayer
      deprecated: false
      security:
        - oauth2:
            - BnetWrite
  /Destiny2/Stats/Definition/:
    get:
      tags:
        - Destiny2
      description: Gets historical stats components/schemas.
      operationId: Destiny2.GetHistoricalStatsDefinition
      deprecated: false
  /Destiny2/Stats/Leaderboards/Clans/{groupId}/:
    get:
      tags:
        - Destiny2
        - Preview
      description:
        "Gets leaderboards with the signed in user's friends and the supplied
        destinyMembershipId as the focus. PREVIEW: This endpoint is still in beta,
        and may experience rough edges. The schema is in final form, but there may
        be bugs that prevent desirable operation."
      operationId: Destiny2.GetClanLeaderboards
      deprecated: false
      x-preview: true
  /Destiny2/Stats/AggregateClanStats/{groupId}/:
    get:
      tags:
        - Destiny2
        - Preview
      description:
        "Gets aggregated stats for a clan using the same categories as
        the clan leaderboards. PREVIEW: This endpoint is still in beta, and may experience
        rough edges. The schema is in final form, but there may be bugs that prevent
        desirable operation."
      operationId: Destiny2.GetClanAggregateStats
      deprecated: false
      x-preview: true
  /Destiny2/{membershipType}/Account/{destinyMembershipId}/Stats/Leaderboards/:
    get:
      tags:
        - Destiny2
        - Preview
      description:
        "Gets leaderboards with the signed in user's friends and the supplied
        destinyMembershipId as the focus. PREVIEW: This endpoint has not yet been
        implemented. It is being returned for a preview of future functionality, and
        for public comment/suggestion/preparation."
      operationId: Destiny2.GetLeaderboards
      deprecated: false
      x-preview: true
  /Destiny2/Stats/Leaderboards/{membershipType}/{destinyMembershipId}/{characterId}/:
    get:
      tags:
        - Destiny2
        - Preview
      description:
        "Gets leaderboards with the signed in user's friends and the supplied
        destinyMembershipId as the focus. PREVIEW: This endpoint is still in beta,
        and may experience rough edges. The schema is in final form, but there may
        be bugs that prevent desirable operation."
      operationId: Destiny2.GetLeaderboardsForCharacter
      deprecated: false
      x-preview: true
  /Destiny2/Armory/Search/{type}/{searchTerm}/:
    get:
      tags:
        - Destiny2
      description: Gets a page list of Destiny items.
      operationId: Destiny2.SearchDestinyEntities
      deprecated: false
  /Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/:
    get:
      tags:
        - Destiny2
      description: Gets historical stats for indicated character.
      operationId: Destiny2.GetHistoricalStats
      deprecated: false
  /Destiny2/{membershipType}/Account/{destinyMembershipId}/Stats/:
    get:
      tags:
        - Destiny2
      description:
        Gets aggregate historical stats organized around each character
        for a given account.
      operationId: Destiny2.GetHistoricalStatsForAccount
      deprecated: false
  /Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/Activities:
    get:
      tags:
        - Destiny2
      description: Gets activity history stats for indicated character.
      operationId: Destiny2.GetActivityHistory
      deprecated: false
  /Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/UniqueWeapons/:
    get:
      tags:
        - Destiny2
      description: Gets details about unique weapon usage, including all exotic weapons.
      operationId: Destiny2.GetUniqueWeaponHistory
      deprecated: false
  /Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/AggregateActivityStats/:
    get:
      tags:
        - Destiny2
      description:
        Gets all activities the character has participated in together
        with aggregate statistics for those activities.
      operationId: Destiny2.GetDestinyAggregateActivityStats
      deprecated: false
  /Destiny2/Milestones/{milestoneHash}/Content/:
    get:
      tags:
        - Destiny2
      description:
        Gets custom localized content for the milestone of the given hash,
        if it exists.
      operationId: Destiny2.GetPublicMilestoneContent
      deprecated: false
  /Destiny2/Milestones/:
    get:
      tags:
        - Destiny2
      description: Gets public information about currently available Milestones.
      operationId: Destiny2.GetPublicMilestones
      deprecated: false
  /Destiny2/Awa/Initialize/:
    post:
      tags:
        - Destiny2
      description: Initialize a request to perform an advanced write action.
      operationId: Destiny2.AwaInitializeRequest
      deprecated: false
      security:
        - oauth2:
            - AdvancedWriteActions
  /Destiny2/Awa/AwaProvideAuthorizationResult/:
    post:
      tags:
        - Destiny2
      description:
        Provide the result of the user interaction. Called by the Bungie
        Destiny App to approve or reject a request.
      operationId: Destiny2.AwaProvideAuthorizationResult
      deprecated: false
  /Destiny2/Awa/GetActionToken/{correlationId}/:
    get:
      tags:
        - Destiny2
      description: Returns the action token if user approves the request.
      operationId: Destiny2.AwaGetActionToken
      deprecated: false
      security:
        - oauth2:
            - AdvancedWriteActions
  /CommunityContent/Get/{sort}/{mediaFilter}/{page}/:
    get:
      tags:
        - CommunityContent
      description: Returns community content.
      operationId: CommunityContent.GetCommunityContent
      deprecated: false
  /Trending/Categories/:
    get:
      tags:
        - Trending
      description:
        Returns trending items for Bungie.net, collapsed into the first
        page of items per category. For pagination within a category, call GetTrendingCategory.
      operationId: Trending.GetTrendingCategories
      deprecated: false
  /Trending/Categories/{categoryId}/{pageNumber}/:
    get:
      tags:
        - Trending
      description: Returns paginated lists of trending items for a category.
      operationId: Trending.GetTrendingCategory
      deprecated: false
  /Trending/Details/{trendingEntryType}/{identifier}/:
    get:
      tags:
        - Trending
      description:
        "Returns the detailed results for a specific trending entry. Note
        that trending entries are uniquely identified by a combination of *both* the
        TrendingEntryType *and* the identifier: the identifier alone is not guaranteed
        to be globally unique."
      operationId: Trending.GetTrendingEntryDetail
      deprecated: false
  /Fireteam/Clan/{groupId}/ActiveCount/:
    get:
      tags:
        - Fireteam
      description:
        Gets a count of all active non-public fireteams for the specified
        clan. Maximum value returned is 25.
      operationId: Fireteam.GetActivePrivateClanFireteamCount
      deprecated: false
      security:
        - oauth2:
            - ReadGroups
  /Fireteam/Clan/{groupId}/Available/{platform}/{activityType}/{dateRange}/{slotFilter}/{publicOnly}/{page}/:
    get:
      tags:
        - Fireteam
      description:
        Gets a listing of all of this clan's fireteams that are have available
        slots. Caller is not checked for join criteria so caching is maximized.
      operationId: Fireteam.GetAvailableClanFireteams
      deprecated: false
      security:
        - oauth2:
            - ReadGroups
  /Fireteam/Search/Available/{platform}/{activityType}/{dateRange}/{slotFilter}/{page}/:
    get:
      tags:
        - Fireteam
      description:
        Gets a listing of all public fireteams starting now with open slots.
        Caller is not checked for join criteria so caching is maximized.
      operationId: Fireteam.SearchPublicAvailableClanFireteams
      deprecated: false
      security:
        - oauth2:
            - ReadGroups
  /Fireteam/Clan/{groupId}/My/{platform}/{includeClosed}/{page}/:
    get:
      tags:
        - Fireteam
      description:
        Gets a listing of all clan fireteams that caller is an applicant,
        a member, or an alternate of.
      operationId: Fireteam.GetMyClanFireteams
      deprecated: false
      security:
        - oauth2:
            - ReadGroups
  /Fireteam/Clan/{groupId}/Summary/{fireteamId}/:
    get:
      tags:
        - Fireteam
      description: Gets a specific clan fireteam.
      operationId: Fireteam.GetClanFireteam
      deprecated: false
      security:
        - oauth2:
            - ReadGroups
  /GetAvailableLocales/:
    get:
      tags:
        - ""
      description: List of available localization cultures
      operationId: .GetAvailableLocales
      deprecated: false
  /Settings/:
    get:
      tags:
        - ""
      description: Get the common settings used by the Bungie.Net environment.
      operationId: .GetCommonSettings
      deprecated: false
  /UserSystemOverrides/:
    get:
      tags:
        - ""
      description:
        Get the user-specific system overrides that should be respected
        alongside common systems.
      operationId: .GetUserSystemOverrides
      deprecated: false
  /GlobalAlerts/:
    get:
      tags:
        - ""
      description:
        Gets any active global alert for display in the forum banners,
        help pages, etc. Usually used for DOC alerts.
      operationId: .GetGlobalAlerts
      deprecated: false

tags:
  - name: App
    description: application
  - name: User
    description: user
  - name: Content
    description: content
  - name: Forum
    description: forum
  - name: GroupV2
    description: groupV2
  - name: Tokens
    description: tokens
  - name: Destiny2
    description: destiny2
  - name: CommunityContent
    description: communitycontent
  - name: Trending
    description: trending
  - name: Fireteam
    description: fireteam
  - name: ""
    description: core
