components:
  schemas:
    DestinyVendorReceiptsComponent:
      type: object
      properties:
        receipts:
          type: array
          description: The receipts for refundable purchases made at a vendor.
          items:
            $ref: "../vendors.yml#/components/schemas/DestinyVendorReceipt"
      description: "For now, this isn't used for much: it's a record of the recent refundable purchases that the user has made. In the future, it could be used for providing refunds/buyback via the API. Wouldn't that be fun?"
      x-destiny-component-type-dependency: VendorReceipts

    DestinyProfileComponent:
      type: object
      properties:
        userInfo:
          type: object
          description: If you need to render the Profile (their platform name, icon, etc...) somewhere, this property contains that information.
          allOf:
            - $ref: "../../user.yml#/components/schemas/UserInfoCard"
        dateLastPlayed:
          type: string
          description: The last time the user played with any character on this Profile.
          format: date-time
        versionsOwned:
          type: integer
          description:
            'If you want to know what expansions they own, this will contain that data.
            IMPORTANT: This field may not return the data you''re interested in for Cross-Saved users. It returns the last ownership data we saw for this account - which is to say, what they''ve purchased on the platform on which they last played, which now could be a different platform.
            If you don''t care about per-platform ownership and only care about whatever platform it seems they are playing on most recently, then this should be "good enough." Otherwise, this should be considered deprecated. We do not have a good alternative to provide at this time with platform specific ownership data for DLC.'
          format: int32
          x-enum-reference:
            $ref: "../../destiny.yml#/components/schemas/DestinyGameVersions"
        characterIds:
          type: array
          description: A list of the character IDs, for further querying on your part.
          items:
            type: integer
            format: int64
        seasonHashes:
          type: array
          description: "
            A list of seasons that this profile owns. Unlike versionsOwned, these stay with the profile across Platforms, and thus will be valid.
            It turns out that Stadia Pro subscriptions will give access to seasons but only while playing on Stadia and with an active subscription. So some users (users who have Stadia Pro but choose to play on some other platform) won't see these as available: it will be whatever seasons are available for the platform on which they last played."
          items:
            type: integer
            format: uint32
          x-mapped-definition:
            $ref: "../definitions/seasons.yml#/components/schemas/DestinySeasonDefinition"
        currentSeasonHash:
          type: integer
          description: If populated, this is a reference to the season that is currently active.
          format: uint32
          x-mapped-definition:
            $ref: "../definitions/seasons.yml#/components/schemas/DestinySeasonDefinition"
        currentSeasonRewardPowerCap:
          type: integer
          description: If populated, this is the reward power cap for the current season.
          format: int32
      description: The most essential summary information about a Profile (in Destiny 1, we called these "Accounts").
      x-destiny-component-type-dependency: Profiles
